### ISSUE TITLE
HW3: Running Valgrind on Cygwin with C++ Code Generated in CLion (Windows)--Cannot Compile in Cygwin

### ISSUE THREAD

**Issue by peterqstorm** [bernardoct/CppTraining#3]
When compiling and running my code in CLion, I am not running into any issues. However, I am trying to run Valgrind to examine the code.

I am attempting to compile the primary function using the following code:
`g++ -O0 -g main.cpp -o main
`

From here, I am getting the following error:
`/tmp/ccMwIo8o.o: In function `main':
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:7: undefi                                                                                                                           ned reference to `Reservoir::Reservoir(std::string const&, double, double, unsig                                                                                                                           ned int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:7:(.text+                                                                                                                           0x69): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `Rese                                                                                                                           rvoir::Reservoir(std::string const&, double, double, unsigned int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:8: undefi                                                                                                                           ned reference to `Reservoir::Reservoir(std::string const&, double, double, unsig                                                                                                                           ned int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:8:(.text+                                                                                                                           0xe3): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `Rese                                                                                                                           rvoir::Reservoir(std::string const&, double, double, unsigned int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:11: undef                                                                                                                           ined reference to `Reservoir::performMassBalance(double, int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:11:(.text                                                                                                                           +0x139): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `Re                                                                                                                           servoir::performMassBalance(double, int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:12: undef                                                                                                                           ined reference to `Reservoir::performMassBalance(double, int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:12:(.text                                                                                                                           +0x166): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `Re                                                                                                                           servoir::performMassBalance(double, int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:14: undef                                                                                                                           ined reference to `StorageInfrastructure::getStored_volumes() const'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:14:(.text                                                                                                                           +0x17b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `St                                                                                                                           orageInfrastructure::getStored_volumes() const'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:14: undef                                                                                                                           ined reference to `StorageInfrastructure::getStored_volumes() const'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:14:(.text                                                                                                                           +0x1c1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `St                                                                                                                           orageInfrastructure::getStored_volumes() const'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:16: undef                                                                                                                           ined reference to `Reservoir::performMassBalance(double, int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:16:(.text                                                                                                                           +0x215): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `Re                                                                                                                           servoir::performMassBalance(double, int)'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:18: undef                                                                                                                           ined reference to `StorageInfrastructure::getStored_volumes() const'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:18:(.text                                                                                                                           +0x221): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `St                                                                                                                           orageInfrastructure::getStored_volumes() const'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:19: undef                                                                                                                           ined reference to `StorageInfrastructure::getStored_volumes() const'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/main.cpp:19:(.text                                                                                                                           +0x25d): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `St                                                                                                                           orageInfrastructure::getStored_volumes() const'
/tmp/ccMwIo8o.o: In function `Reservoir::~Reservoir()':
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/Infrastructure/Res                                                                                                                           ervoir.h:10: undefined reference to `StorageInfrastructure::~StorageInfrastructu                                                                                                                           re()'
/cygdrive/e/Dropbox/Dropbox/Reed Group Work/cpp_training/mb_3/Infrastructure/Res                                                                                                                           ervoir.h:10:(.text$_ZN9ReservoirD1Ev[_ZN9ReservoirD1Ev]+0x26): relocation trunca                                                                                                                           ted to fit: R_X86_64_PC32 against undefined symbol `StorageInfrastructure::~Stor                                                                                                                           ageInfrastructure()'
/tmp/ccMwIo8o.o:main.cpp:(.rdata$.refptr._ZTV9Reservoir[.refptr._ZTV9Reservoir]+                                                                                                                           0x0): undefined reference to `vtable for Reservoir'
collect2: error: ld returned 1 exit status
`

I was curious if you had any suggestions with how to proceed.

Thanks!

**Comment by bernardoct** [comment]
You should try running Valgrind from CLion itself (will work if you have Ubuntu terminal installed. Otherwise, you have to compile all cpp and header files all at once, which you can do with:
```
g++ main.cpp directory/file2.cpp directory/file2.h -o my_model -Wall
```
Alternatively, if all you have in your directories are cpp and header files, you can use the following command:
```
g++ main.cpp directory/* -o my_model -Wall
```

Let me know if that works

**Comment by peterqstorm** [comment]
Once I only moved over the relevant files (i.e. .cpp and header files) into a new directory, I was able to run the second command as:

`g++ main.cpp Infrastructure/* -o my_model -Wall
`

However, I am receiving the following issue that I am not sure why it is popping up (bold is where cygwin is underlining it):

`
Infrastructure/StorageInfrastructure.cpp: In constructor ‘StorageInfrastructure::StorageInfrastructure(const string&, double, double, unsigned int)’:
Infrastructure/StorageInfrastructure.cpp:19:23: **warning**: comparison between signed and unsigned integer expressions [**-Wsign-compare**]
     for (int t = 0; **t < simulated_time**; ++t) {

`

Any thoughts on this end?

**Comment by bernardoct** [comment]
It's as the warning "comparison between signed and unsigned integer" says: you're comparing "int t," which is integer (and therefore signed +/-) with simulated_time, which I'm assuming is "unsigned long/int." You can fix this by either declaring **simulated_time as an integer** (which what I would do, I forgot about this issue last week during training) or my having your for loop as ```for (unsigned long t = 0; t < ...```.

**Comment by peterqstorm** [comment]
Thanks, I fixed those and the error stopped!

To get valgrind to work, I decided to just run everything on TheCube.
